#!/bin/bash

# =================================================================
# ClouDNS Daily Auto-Updater (UTC+8)
# 一鍵設定 ClouDNS 每日定時更新腳本
#
# 功能：
# 1. 自動校正系統時區為 Asia/Taipei (UTC+8)
# 2. 互動式輸入 ClouDNS Dynamic URL
# 3. 指定每日執行時間 (HH:MM)
# 4. 自動設定 Crontab 排程
# =================================================================

# --- 顏色定義 ---
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

clear
echo -e "${GREEN}#################################################${NC}"
echo -e "${GREEN}#      ClouDNS DDNS 每日定時任務設定精靈        #${NC}"
echo -e "${GREEN}#     (Daily Update / UTC+8 Timezone Support)   #${NC}"
echo -e "${GREEN}#################################################${NC}"

# 1. 檢查 Root 權限
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}[Error] 請使用 root 權限執行此腳本 (sudo -i)${NC}"
  exit 1
fi

# 2. 設定時區 (確保是東八區 UTC+8)
echo -e "\n${CYAN}>>> 正在校正系統時區為 東八區 (Asia/Taipei)...${NC}"
if command -v timedatectl &> /dev/null; then
    timedatectl set-timezone Asia/Taipei
else
    ln -sf /usr/share/zoneinfo/Asia/Taipei /etc/localtime
fi
echo -e "✅ 當前系統時間: $(date '+%Y-%m-%d %H:%M:%S')"

# 3. 步驟一：詢問 DDNS 金鑰 (URL)
echo -e "\n${YELLOW}【步驟 1】設定 DDNS 金鑰${NC}"
echo "請輸入您的 ClouDNS Dynamic URL (例如: https://ipv4.cloudns.net/...)"
read -p "URL: " DDNS_URL

if [[ -z "$DDNS_URL" ]]; then
    echo -e "${RED}[Error] URL 不能為空！${NC}"
    exit 1
fi

# 4. 步驟二：詢問每日執行時間
echo -e "\n${YELLOW}【步驟 2】設定每天啟動時間 (24小時制)${NC}"
read -p "請問要每天幾點執行? (輸入 0-23): " RUN_HOUR
read -p "請問要幾分執行? (輸入 0-59): " RUN_MINUTE

if ! [[ "$RUN_HOUR" =~ ^[0-9]+$ ]] || ! [[ "$RUN_MINUTE" =~ ^[0-9]+$ ]]; then
    echo -e "${RED}[Error] 時間格式錯誤，請輸入數字！${NC}"
    exit 1
fi

# 5. 步驟三：部署腳本
echo -e "\n${CYAN}>>> 正在部署自動化腳本...${NC}"

TARGET_SCRIPT="/usr/local/bin/cloudns_daily_update.sh"
LOG_FILE="/var/log/cloudns_ddns.log"

# 建立實際執行的腳本
cat > "$TARGET_SCRIPT" <<ENDSCRIPT
#!/bin/bash
# Auto-generated by setup script
# Run Time: Daily at $RUN_HOUR:$RUN_MINUTE

NOW=\$(date '+%Y-%m-%d %H:%M:%S')
RESPONSE=\$(curl -s -w "%{http_code}" "$DDNS_URL")

if [[ "\$RESPONSE" == *"200"* ]]; then
    echo "\$NOW [SUCCESS] DDNS Updated (HTTP 200)" >> $LOG_FILE
else
    echo "\$NOW [FAIL] DDNS Update Error (HTTP \$RESPONSE)" >> $LOG_FILE
fi

# Log Rotation (Keep last 50 lines)
tail -n 50 $LOG_FILE > ${LOG_FILE}.tmp && mv ${LOG_FILE}.tmp $LOG_FILE
ENDSCRIPT

chmod +x "$TARGET_SCRIPT"

# 6. 設定 Crontab
CRON_CMD="$RUN_MINUTE $RUN_HOUR * * * $TARGET_SCRIPT"
(crontab -l 2>/dev/null | grep -v "cloudns_daily_update.sh"; echo "$CRON_CMD") | crontab -

echo -e "\n${GREEN}🎉 設定完成 (Setup Complete)！${NC}"
echo -e "----------------------------------------------------"
echo -e "📅 頻率 (Freq): 每天 (Daily)"
echo -e "⏰ 時間 (Time): ${YELLOW}${RUN_HOUR}:${RUN_MINUTE}${NC} (Asia/Taipei)"
echo -e "📄 腳本 (Script): $TARGET_SCRIPT"
echo -e "📝 日誌 (Log): $LOG_FILE"
echo -e "----------------------------------------------------"

echo -e "\n正在執行連線測試..."
$TARGET_SCRIPT
echo -e "測試結束，請檢查日誌。"
